# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userID', models.CharField(max_length=255, unique=True, verbose_name='userID')),
                ('username', models.CharField(max_length=20, verbose_name='username')),
                ('email', models.EmailField(max_length=255, null=True, verbose_name='email address')),
                ('loginType', models.CharField(max_length=20, verbose_name='loginType')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'api_user',
                'swappable': 'AUTH_USER_MODEL',
            },
        ),
    ]
