# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_grouop'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grouop',
            new_name='Group',
        ),
    ]
